### ISSUE TITLE
nvcc not found

### ISSUE THREAD

**Issue by ron5569** [Scalsol/mega.pytorch#11]
Hey
I follow the install instruction but when I tried to install apex I got the followng error:

    raise RuntimeError("--cuda_ext was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.")
RuntimeError: --cuda_ext was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.

I tried to specify CUDAHOME but I got message

 raise RuntimeError("Cuda extensions are being compiled with a version of Cuda that does not match the version used to compile Pytorch binaries.  Pytorch binaries were compiled with Cuda 10.0.130.
In some cases, a minor-version mismatch will not cause later errors:  https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  You can try commenting out this check at your own risk ")

Any suggestion? 
Thanks!

**Comment by Scalsol** [comment]
maybe you should run command `nvcc --version` first to see your cuda version? The insturction I give installs pytorch with cuda 10.0 which may not be your cuda version. I suggest you to check that first.

**Comment by amousist** [comment]
@ron5569 I have the same issue. How did you solve it?
