### ISSUE TITLE
How to train MEGA on my own dataset？

### ISSUE THREAD

**Issue by ZJU-lishuang** [Scalsol/mega.pytorch#13]

**Comment by Scalsol** [comment]
You should organize your dataset like ImageNet VID and generate imageset files just like those in `datasets/ILSVRC2015/ImageSets`. For example, in `VID_train_15frames.txt`, every line contains 4 strings, each representing *video folder*, *no meaning*(but I still keep it), *frame number*, *video length*. You could check the dataset for further details.

**Comment by ZJU-lishuang** [comment]
where does it need to be modified if the number of categories has changed?

`NUM_CLASSES` in `configs/BASE_RCNN_{}gpu.yaml`
`classes` and `classes_map` in `mega_core/data/datasets/vid.py`

Does any other place need?

**Comment by Scalsol** [comment]
> 
> 
> where does it need to be modified if the number of categories has changed?
> 
> `NUM_CLASSES` in `configs/BASE_RCNN_{}gpu.yaml`
> `classes` and `classes_map` in `mega_core/data/datasets/vid.py`
> 
> Does any other place need?

I think it's enough.

**Comment by ZJU-lishuang** [comment]
How to test MEGA if current frame could only access information from previous frames？
Where does it need to be modified?

**Comment by Scalsol** [comment]
For local frame, change `MEGA.MAX_OFFSET` to zero, `MEGA.KEY_FRAME_LOCATION` to `-MEGA.MIN_OFFSET` and `MEGA.ALL_FRAME_INTERVAL` to `-MEGA.MIN_OFFSET + 1`. For global frame there is no elegant way to modify the current code to support that. One way to acheive this is to keep a queue to store all previous frame, and randomly select several of them when testing. Hope this helps.

**Comment by ZJU-lishuang** [comment]
Thanks for your  help.I will have a try.

**Comment by HzZHoO** [comment]
> _No description provided._

Sorry to bother you. 
May I ask you about the way that you annotate your own dataset? Does your dataset has annotations for every frame of the videos just like the VID dataset?

**Comment by ZJU-lishuang** [comment]
yes，the dataset is just like VID dataset.

**Comment by Dawn-LX** [comment]
> where does it need to be modified if the number of categories has changed?
> 
> `NUM_CLASSES` in `configs/BASE_RCNN_{}gpu.yaml`
> `classes` and `classes_map` in `mega_core/data/datasets/vid.py`
> 
> Does any other place need?

Thank you very much!, I only modified the `classes` and `classes_map` in `mega_core/data/datasets/vid.py`;  and I  encountered a RuntimeError:
``RuntimeError: copy_if failed to synchronize: device-side assert triggered``
``CUDA error 59: Device-side assert triggered``

Then I modified the `NUM_CLASSES` in `configs/BASE_RCNN_{}gpu.yaml` to the corresponding number of classes and the problem fixed

**Comment by Jezzzzz** [comment]
> yes，the dataset is just like VID dataset.

Hi，how do you annotate  your dataset like the VID dataset?

**Comment by ZJU-lishuang** [comment]
labelimg is enough
