### ISSUE TITLE
model predict class that is not exist

### ISSUE THREAD

**Issue by ron5569** [Scalsol/mega.pytorch#14]
Hey
I try to train model with a single class (pedestrian)
I change the variables in  file mega_core/data/datasets/vid.py
so it look like that
    classes = ['__background__', "person"]
    classes_map = ['0.0', 'person']

however, In some cases I got files that has classes index like 12, 26, etc..
Am I doing it right?

**Comment by ron5569** [comment]
found it
there is NUM_CLASSES in BASE_RCNN_xgpu.yaml file 
:)

**Comment by hyperparameters** [comment]
@ron5569 what dataset are you using? how does if performs? 
can you share the metrics
