### ISSUE TITLE
Evaluation on slow, medium, and fast motion group

### ISSUE THREAD

**Issue by wcy116** [Scalsol/mega.pytorch#15]
Thanks for your excellent work and nice open-source code. Do you mind adding the evaluation on the slow, medium, and fast motion group as shown in FGFA? It may be useful for further research in the field of video object detection.

**Comment by Scalsol** [comment]
As now I'm working on another project so I have no time to add motion specific evaluation metric... After that I'll try to implement that. You could try to implement by yourself at this moment :)

**Comment by Scalsol** [comment]
I've added motion-IoU specific evaluation code. Enjoy it :)
