### ISSUE TITLE
test on a video file

### ISSUE THREAD

**Issue by kaishijeng** [Scalsol/mega.pytorch#18]
I like to use your pretrained model to do object detection on a MP4 video file.
tools/test_net.py is for validation because it needs target files which can not be used for my mp4 video file. 
Any suggestion?

Thanks,

**Comment by kaishijeng** [comment]
@Scalsol 

   Any help you can give?

Thanks

**Comment by Scalsol** [comment]
Sorry for late reply! You may refer to [mmdetection](https://github.com/open-mmlab/mmdetection/blob/master/docs/getting_started.md#synchronous-interface) to see how they inference on a piece of video and adjust some code of this repo accordingly to achieve the behavior you want. After the NIPS ddl I will try to add demo to enable inference on video files but currently I have no time :( Hope this piece of message would help!

**Comment by kaishijeng** [comment]
I will take a look at mmdetection code and  try to do it myself.
In the meantime, it will be great that you can add one after NIPS in case I am not able to do it

Thanks,

**Comment by SonrLax** [comment]
@Scalsol Since MEGA is based on maskrcnn_benchmark, why not refer to [demo](https://github.com/facebookresearch/maskrcnn-benchmark/tree/master/demo) ?  Just curious. 
Thanks !

**Comment by Scalsol** [comment]
@SonrLax Because when MEGA makes a prediction, it doesn't rely only on just one image, so the demo is not directly applicable. I need to preprocess the whole video into a queue and sequentially process them. It's not hard but a bit tricky. :)

**Comment by kaishijeng** [comment]
@Scalsol 

  No need to support one single image. Just video is OK.

Thanks,

**Comment by Scalsol** [comment]
I've added demo for visualization, closing this. Feel free to reopen it if the visualization doesn't work :)

**Comment by guermal** [comment]
!hi, I get segmentation fault whenever i try to do demo on my video, or i get Imagelist not scriptable any help please ?

**Comment by yzhao520** [comment]
> !hi, I get segmentation fault whenever i try to do demo on my video, or i get Imagelist not scriptable any help please ?

I just run into the same issue. Do you have a solution to this problem?
