### ISSUE TITLE
Can this repository implement the other algorithm TFAN?

### ISSUE THREAD

**Issue by ZJU-lishuang** [Scalsol/mega.pytorch#19]
[TFAN](https://cse.buffalo.edu/~jsyuan/papers/2020/TFAN.pdf)

**Comment by ZJU-lishuang** [comment]
[TFAN](https://cse.buffalo.edu/~jsyuan/papers/2020/TFAN.pdf)

**Comment by Scalsol** [comment]
I'm not familar with TFAN but it seems compatible with this repo (though the task TFAN aims at is somewhat different with general video object detection). Anyway, feel free to use this repo to do anything :)
