### ISSUE TITLE
Imagenet VID Metric

### ISSUE THREAD

**Issue by Westerby** [Scalsol/mega.pytorch#20]
Hello,

I wanted to ask how the metric you use in this paper (and many other use with regard to Imagenet VID dataset) relate to COCO dataset metric? Is this simply IoU=0.50 metric (a second metric in cocotools printout/PASCAL VOC threshold?)  Or is it loosened metric as mentioned [here](https://arxiv.org/pdf/1907.09408.pdf) - page 11?  

By the way, great repository! Thank you for uploading it to Git!

**Comment by Scalsol** [comment]
Thank you for your interest! The metric here we used is the simple IoU=0.50 metric. The loosened metric your mentioned is the metric used in the old MXNet version [FGFA](https://github.com/msracver/Flow-Guided-Feature-Aggregation/issues) repo. The value of the loosened metric would be a little higher than the simple IoU=0.50 metric but is not significant, so we choose the simple one.

**Comment by Westerby** [comment]
Thanks for the response!
