### ISSUE TITLE
Very low mAp, is something wrong?

### ISSUE THREAD

**Issue by chengrongliang** [Scalsol/mega.pytorch#21]
I had processed the inference:
```
python -m torch.distributed.launch \
    --nproc_per_node 4 \
    tools/test_net.py \
    --config-file configs/MEGA/vid_R_101_C4_MEGA_1x.yaml \
    MODEL.WEIGHT MEGA_R_101.pth 
```
However, i got very low mAP,:
```
mega_core.inference INFO: mAP: 0.2637
airplane        : 0.0199
antelope        : 0.2227
bear            : 0.3345
bicycle         : 0.1707
bird            : 0.1427
bus             : 0.0666
car             : 0.1543
cattle          : 0.4041
dog             : 0.1296
domestic_cat    : 0.4953
elephant        : 0.3495
fox             : 0.4683
giant_panda     : 0.3769
hamster         : 0.4125
horse           : 0.0388
lion            : 0.1511
lizard          : 0.3799
monkey          : 0.2813
motorcycle      : 0.0661
rabbit          : 0.5833
red_panda       : 0.5000
sheep           : 0.0673
snake           : 0.4717
squirrel        : 0.0557
tiger           : 0.5354
train           : 0.3820
turtle          : 0.0911
watercraft      : 0.2108
whale           : 0.0651
zebra           : 0.2824
```
is something wrong?

**Comment by Scalsol** [comment]
It is weird. I just re-tested my model and the result is normal, shown below:
```
mAP: 0.8296
airplane        : 0.9132
antelope        : 0.8447
bear            : 0.9107
bicycle         : 0.7732
bird            : 0.7687
bus             : 0.8600
car             : 0.6413
cattle          : 0.8615
dog             : 0.8291
domestic_cat    : 0.9286
elephant        : 0.8603
fox             : 0.9856
giant_panda     : 0.8931
hamster         : 0.9863
horse           : 0.8386
lion            : 0.8577
lizard          : 0.8430
monkey          : 0.6028
motorcycle      : 0.8528
rabbit          : 0.8065
red_panda       : 0.8882
sheep           : 0.6720
snake           : 0.8088
squirrel        : 0.6043
tiger           : 0.9127
train           : 0.8834
turtle          : 0.8336
watercraft      : 0.6789
whale           : 0.7871
zebra           : 0.9615
```
Maybe the model is not loaded successfully? If possible, please paste full output after running the command line then I could help locate the problem.

**Comment by chengrongliang** [comment]
> It is weird. I just re-tested my model and the result is normal, shown below:
> 
> ```
> mAP: 0.8296
> airplane        : 0.9132
> antelope        : 0.8447
> bear            : 0.9107
> bicycle         : 0.7732
> bird            : 0.7687
> bus             : 0.8600
> car             : 0.6413
> cattle          : 0.8615
> dog             : 0.8291
> domestic_cat    : 0.9286
> elephant        : 0.8603
> fox             : 0.9856
> giant_panda     : 0.8931
> hamster         : 0.9863
> horse           : 0.8386
> lion            : 0.8577
> lizard          : 0.8430
> monkey          : 0.6028
> motorcycle      : 0.8528
> rabbit          : 0.8065
> red_panda       : 0.8882
> sheep           : 0.6720
> snake           : 0.8088
> squirrel        : 0.6043
> tiger           : 0.9127
> train           : 0.8834
> turtle          : 0.8336
> watercraft      : 0.6789
> whale           : 0.7871
> zebra           : 0.9615
> ```
> 
> Maybe the model is not loaded successfully? If possible, please paste full output after running the command line then I could help locate the problem.

Hi,

**Comment by chengrongliang** [comment]
@Scalsol Sorry for closing the issue. 
I re-download the model file and check the model(MEGA_R_101.pth) again， It has same problems, However, I tested the DFF is OK. MEGA inference log file has been sent to your  `@pku.edu.cn` mail.

**Comment by Westerby** [comment]
Hello,
I had similar problem yesterday. I wanted to replicate the base training with the command:
`python -m torch.distributed.launch --nproc_per_node=8 tools/train_net.py --master_port=$((RANDOM + 10000)) --config-file configs/BASE_RCNN_8gpu.yaml OUTPUT_DIR training_dir/RES50`

I didn't change anything in code or in original coding. Here's the output I got:

```
2020-05-13 21:09:47,512 mega_core.inference INFO: mAP: 0.1334
airplane        : 0.5727
antelope        : 0.0172
bear            : 0.1196
bicycle         : 0.1209
bird            : 0.0127
bus             : 0.2079
car             : 0.1866
cattle          : 0.1321
dog             : 0.0806
domestic_cat    : 0.0766
elephant        : 0.3049
fox             : 0.1000
giant_panda     : 0.3358
hamster         : 0.0889
horse           : 0.1572
lion            : 0.0002
lizard          : 0.0547
monkey          : 0.0504
motorcycle      : 0.0694
rabbit          : 0.0596
red_panda       : 0.0230
sheep           : 0.1605
snake           : 0.0466
squirrel        : 0.0105
tiger           : 0.0742
train           : 0.1285
turtle          : 0.2168
watercraft      : 0.0508
whale           : 0.2086
zebra           : 0.3343
```

What seems to be the problem? Is the steps parameter in original config set as too low?

**Comment by Scalsol** [comment]
> 
> 
> Hello,
> I had similar problem yesterday. I wanted to replicate the base training with the command:
> `python -m torch.distributed.launch --nproc_per_node=8 tools/train_net.py --master_port=$((RANDOM + 10000)) --config-file configs/BASE_RCNN_8gpu.yaml OUTPUT_DIR training_dir/RES50`
> 
> I didn't change anything in code or in original coding. Here's the output I got:
> 
> ```
> 2020-05-13 21:09:47,512 mega_core.inference INFO: mAP: 0.1334
> airplane        : 0.5727
> antelope        : 0.0172
> bear            : 0.1196
> bicycle         : 0.1209
> bird            : 0.0127
> bus             : 0.2079
> car             : 0.1866
> cattle          : 0.1321
> dog             : 0.0806
> domestic_cat    : 0.0766
> elephant        : 0.3049
> fox             : 0.1000
> giant_panda     : 0.3358
> hamster         : 0.0889
> horse           : 0.1572
> lion            : 0.0002
> lizard          : 0.0547
> monkey          : 0.0504
> motorcycle      : 0.0694
> rabbit          : 0.0596
> red_panda       : 0.0230
> sheep           : 0.1605
> snake           : 0.0466
> squirrel        : 0.0105
> tiger           : 0.0742
> train           : 0.1285
> turtle          : 0.2168
> watercraft      : 0.0508
> whale           : 0.2086
> zebra           : 0.3343
> ```
> 
> What seems to be the problem? Is the steps parameter in original config set as too low?

1. The config file should be `vid_R_50_C4_1x.yaml ` not `BASE_RCNN_8gpu.yaml`
2. Is the inference carried only on `555` images? That is, does the following line occurs in the output after you ran the command line?
```
mega_core.inference INFO: Start evaluation on VID_val_videos dataset(555 images).
```
This is a weird problem, the inference should be carried on 176126 images (555 is the number of video snippets). I haven't encounter this problem so I suggest you to check your data structure.

**Comment by chengrongliang** [comment]
OMG!!! 
@Scalsol Sorry for replying late. Following in your instruction, I got the correct results, mAP:0.8295. Waiting for 3 hours, it's long time :( . Thanks for your help.

```
2020-05-14 16:17:56,720 mega_core.inference INFO: mAP: 0.8295
airplane        : 0.9124
antelope        : 0.8440
bear            : 0.9125
bicycle         : 0.7717
bird            : 0.7696
bus             : 0.8573
car             : 0.6401
cattle          : 0.8619
dog             : 0.8311
domestic_cat    : 0.9281
elephant        : 0.8598
fox             : 0.9836
giant_panda     : 0.8901
hamster         : 0.9860
horse           : 0.8375
lion            : 0.8575
lizard          : 0.8426
monkey          : 0.6029
motorcycle      : 0.8549
rabbit          : 0.8051
red_panda       : 0.8918
sheep           : 0.6745
snake           : 0.8106
squirrel        : 0.6027
tiger           : 0.9144
train           : 0.8820
turtle          : 0.8334
watercraft      : 0.6797
whale           : 0.7858
zebra           : 0.9608
```

@Westerby please using the correct image list in `mega.pytorch/datasets/ILSVRC2015/ImageSets/`.

**Comment by Scalsol** [comment]
@chengrongliang Glad you've solved this problem :)

**Comment by Westerby** [comment]
@Scalsol 
Thank you for your response. I will train with the other config and get back.
And no, the validation was carried on the whole validation dataset >170k images.

**Comment by Westerby** [comment]
@Scalsol 
Great it worked!

```
2020-05-14 10:45:21,428 mega_core.inference INFO: Start evaluation on VID_val_frames dataset(176126 images).
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22016/22016 [16:10<00:00, 22.67it/s]
2020-05-14 11:02:16,911 mega_core.inference INFO: Total run time: 0:16:55.482245 (0.0461252623567217 s / img per device, on 8 devices)
2020-05-14 11:02:16,912 mega_core.inference INFO: Model inference time: 0:15:20.021986 (0.041789263857432604 s / img per device, on 8 devices)
2020-05-14 11:03:19,230 mega_core.inference INFO: performing vid evaluation, ignored iou_types.
defaultdict(<class 'int'>, {2: 7968, 5: 9862, 9: 20237, 12: 9092, 14: 5476, 17: 5972, 20: 5898, 22: 4405, 23: 6393, 27: 5761, 18: 10654, 16: 2840, 4: 8854, 24: 12088, 25: 2614, 30: 6910, 7: 26690, 3: 9780, 15: 7939, 1: 26387, 6: 6313, 10: 11629, 11: 11934, 19: 1139, 26: 13095, 28: 6089, 29: 7379, 13: 7593, 8: 11365, 21: 1149})
2020-05-14 11:05:40,714 mega_core.inference INFO: mAP: 0.7088
airplane        : 0.9096
antelope        : 0.8201
bear            : 0.7025
bicycle         : 0.6656
bird            : 0.7042
bus             : 0.7073
car             : 0.6251
cattle          : 0.6448
dog             : 0.6469
domestic_cat    : 0.7999
elephant        : 0.7690
fox             : 0.8286
giant_panda     : 0.8703
hamster         : 0.9075
horse           : 0.6927
lion            : 0.1923
lizard          : 0.7561
monkey          : 0.4483
motorcycle      : 0.7976
rabbit          : 0.5668
red_panda       : 0.7155
sheep           : 0.5943
snake           : 0.6516
squirrel        : 0.4848
tiger           : 0.8746
train           : 0.8161
turtle          : 0.7752
watercraft      : 0.6685
whale           : 0.7449
zebra           : 0.8823
```
