### ISSUE TITLE
Duplicated file names in DET_train_30classes.txt

### ISSUE THREAD

**Issue by duanzhiihao** [Scalsol/mega.pytorch#23]
It seems that there are duplicated images in `datasets/ILSVRC2015/ImageSets/DET_train_30classes.txt`, which can be confirmed by the following script.

```python
lines = open('DET_train_30classes.txt', 'r').read().strip().split('\n')
print(len(lines))
# 53639
print(len(set(lines)))
# 53237
```

Is there a reason that you use duplicated training images?

**Comment by Scalsol** [comment]
This file is directly copied from the FGFA repo and I did not check whether duplicated training images exist. This would not influence the final performance in my opinion.

**Comment by duanzhiihao** [comment]
Thanks, I agree.
