### ISSUE TITLE
RunTimeError: CUDA out of memory

### ISSUE THREAD

**Issue by wasif1508** [Scalsol/mega.pytorch#32]
Hi,
I have a NVIDIA-1050Ti (4 GB) GPU. I was running the demo script. It worked perfectly fine for single-frame-baseline however for the "mega" method I am getting the error
 `CUDA out of memory. Tried to allocate 396.00 MiB (GPU 0; 3.95 GiB total capacity; 1.89 GiB already allocated; 384.75 MiB free; 650.19 MiB cached)`
 Are there any parameters in the configuration files that could be modified to make it work? Any help would be appreciated. Thanks in advance.

**Comment by Scalsol** [comment]
All configs related to "mega" are defined [here](https://github.com/Scalsol/mega.pytorch/blob/master/mega_core/config/defaults.py) under prefix `_C.MODEL.VID.MEGA`. For your case, you may need to reduce the size of the memory by setting `_C.MODEL.VID.MEGA.MEMORY.SIZE` to a smaller number or disable memory by setting `_C.MODEL.VID.MEGA.MEMORY.ENABLE` to False. The memory and the relation calculation consumes a lot of memory so with these modification the memory issue may be resolved. But also the performance will degrade. 
If the memory is still not enough, maybe you could try to modify other configs like `_C.MODEL.VID.MEGA.MIN_OFFSET`, `_C.MODEL.VID.MEGA.MAX_OFFSET`. But make sure that `_C.MODEL.VID.MEGA.ALL_FRAME_INTERVAL` equals to `_C.MODEL.VID.MEGA.MAX_OFFSET` - `_C.MODEL.VID.MEGA.MIN_OFFSET`, and `_C.MODEL.VID.MEGA.KEY_FRAME_LOCATION` = -`_C.MODEL.VID.MEGA.MIN_OFFSET`. Or just use a smaller model.

Hope this helps.

**Comment by wasif1508** [comment]
@Scalsol Thanks for help, it works
