### ISSUE TITLE
whats the parameter 'us' mean?

### ISSUE THREAD

**Issue by JTRNEO** [Scalsol/mega.pytorch#33]
HI ,
When I read the code, the MEGA code has a parameter 'us' in its attention module.This is different from that in the Relation Networks for Object Detection paper. What is the meaning of the this parameter?
https://github.com/Scalsol/mega.pytorch/blob/a47df6d5af731eeb690756768f834738e93f504a/mega_core/modeling/roi_heads/box_head/roi_box_feature_extractors.py#L522

**Comment by Scalsol** [comment]
This is a parameter given in Transformer-XL [paper](https://arxiv.org/abs/1901.02860), you could find the original meaning there in Section 3.3. I add it just want to see whether this parameter introduced in that paper helpful here but its effect is negligible here... Simply deleting it should also work fine.
