### ISSUE TITLE
Questions about training set

### ISSUE THREAD

**Issue by ericayn** [Scalsol/mega.pytorch#38]
Hello, I see that when you train the MEGA model, you sample once every 10 frames to consistent training set (datasets/ILSVRC2015/ImageSets/VID_train_every10frame.txt). FGFA methods also sample the training set (VID_train_15frame.txt). However, these two methods have propagated feature to adjacent frames, but samples in VID_train_every10frame.txt have lost the characteristics of adjacent frames. Does MEGA not require continuous image during training model?
I am very confused about this. Could you please help me to answer this?

**Comment by ericayn** [comment]
I solved this.

**Comment by Sanku-Yogesh** [comment]
hi, could u please answer to this query https://github.com/Scalsol/mega.pytorch/issues/73#issue-754884469

**Comment by Sanku-Yogesh** [comment]
@ericayn
