### ISSUE TITLE
no map?

### ISSUE THREAD

**Issue by dylan110** [Scalsol/mega.pytorch#39]
hello, when I run the test_net.py over, why is there no map prediction? 
and there shows
if motion_iou[gt_index] < motion_range[0] or motion_iou[gt_index] > motion_range[1]:
IndexError: list index out of range

**Comment by Scalsol** [comment]
Are you using another dataset? If so, the mAP evaluation is not valid for other dataset now, I will fix this problem ASAP. Or you could try to checkout at this commit https://github.com/Scalsol/mega.pytorch/tree/ec290e4acd1b45b95a9f76dcc18d17f37990c5d7

**Comment by dylan110** [comment]
I evaluate the map in the VID datasets of 555 images, but there still exits no mAP calculation at final phase of the inference. Could you provide some suggestions?

**Comment by Scalsol** [comment]
555 is a wrong number，it should be 176126. You should redownload the txt file for evaluation.

**Comment by dylan110** [comment]
Thank you very much! I will try this.

**Comment by joe660** [comment]
> Are you using another dataset? If so, the mAP evaluation is not valid for other dataset now, I will fix this problem ASAP. Or you could try to checkout at this commit https://github.com/Scalsol/mega.pytorch/tree/ec290e4acd1b45b95a9f76dcc18d17f37990c5d7

请问现在修复了自己数据集计算MAP的算法吗？？

**Comment by LuoXiang-LX** [comment]
现在修复了自己的数据集计算MAP的算法吗？
