### ISSUE TITLE
custom dataset test

### ISSUE THREAD

**Issue by huanyuxinchen** [Scalsol/mega.pytorch#43]
Hi @Scalsol 
       Thanks for your great work. I created my custom dataset like VIDDataset and VIDMEGADataset for training and testing. Now, the training is finished, when I want to test like VID, I found the vid has a vid_ground_truth_motion_iou.mat file, how can I generate my own mat file or how can I avoid using this file? Thank you very much.

**Comment by Scalsol** [comment]
simply deleting the `--motion-specific` argument is enough.

**Comment by huanyuxinchen** [comment]
I think my codebase is not the newest, because the mat file does not rely on the --motion-specific argument. I will check the newest codebase. Thank you very much.
