### ISSUE TITLE
ResNeXt-101 pre-trained model & post-processing

### ISSUE THREAD

**Issue by JohannesTK** [Scalsol/mega.pytorch#6]
Hi,

Thank you for such a well-written paper & open-sourcing your work! 🤗

1. Do you also plan to open-source the pre-trained model with ResNeXt-101 backbone?

2. In the paper it's stated

> Here the post processing technique we adopt is BLR [7], which is done by finding optimal paths in the whole video and then re-score detection boxes in each path. Table 2 summarizes the results of state of-the-art methods with different post-processing techniques.

Is the score **MEGA (ours) ResNeXt-101 85.4** combination of SeqNMS, Tube Rescoring, BLR or only BLR?

Thanks & stay healthy,
Johannes

**Comment by Scalsol** [comment]
Thank you for your interest!
1. Since we have changed our model structure so there is no ResNeXt weight available now (we haven't retrained it). So recently we will not release the ResNeXt-101 weight. They may be available someday :)
2. We only use BLR.

**Comment by JohannesTK** [comment]
Thanks for the reply!
