### ISSUE TITLE
Some error for test.py

### ISSUE THREAD

**Issue by kelisiya** [Scalsol/mega.pytorch#7]
When I want to load  MEGA_R_101.pth;
```2020-04-02 08:48:07,622 mega_core.utils.checkpoint INFO: Loading checkpoint from MEGA_R_101.pth

2020-04-02 08:48:13,503 mega_core.utils.model_serialization INFO:
backbone.body.layer1.0.bn1.bias loaded from backbone.body.layer1.0.bn1.bias of shape (64,)

2020-04-02 08:48:13,503 mega_core.utils.model_serialization INFO: backbone.body.layer1.0.bn1.running_mean loaded from backbone.body.layer1.0.bn1.running_mean                                
 of shape (64,)

2020-04-02 08:48:13,503 mega_core.utils.model_serialization INFO: backbone.body.layer1.0.bn1.running_var loaded from backbone.body.layer1.0.bn1.running_var of shape (64,)

2020-04-02 08:48:13,503 mega_core.utils.model_serialization INFO: backbone.body.layer1.0.bn1.weight loaded from backbone.body.layer1.0.bn1.weight of shape (64,)

2020-04-02 08:48:13,504 mega_core.utils.model_serialization INFO: backbone.body.layer1.0.bn2.bias  loaded from backbone.body.layer1.0.bn2.bias of shape (64,)

RuntimeError: Error(s) in loading state_dict for GeneralizedRCNNMEGA:
size mismatch for rpn.anchor_generator.cell_anchors.0: copying a param with shape torch.Size([12, 4]) from checkpoint, the shape in current model is torch.Size([15, 4]).
size mismatch for rpn.head.cls_logits.weight: copying a param with shape torch.Size([12, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([15, 1024, 1, 1]).
size mismatch for rpn.head.cls_logits.bias: copying a param with shape torch.Size([12]) from checkpoint, the shape in current model is torch.Size([15]).
size mismatch for rpn.head.bbox_pred.weight: copying a param with shape torch.Size([48, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([60, 1024, 1, 1]).```

**Comment by Scalsol** [comment]
it works fine for me. The error you met seems like you are using 5 scales in RPN so the calculated size is 3*5=15. But it should be 4 scales set in `configs/BASE_RCNN_{}4gpu.yaml` which is loaded in L70 in `tools/test_net.py`. I suggest you to check your config file.

**Comment by kelisiya** [comment]
> it works fine for me. The error you met seems like you are using 5 scales in RPN so the calculated size is 3*5=15. But it should be 4 scales set in `configs/BASE_RCNN_{}4gpu.yaml` which is loaded in L70 in `tools/test_net.py`. I suggest you to check your config file.

thanks,it's my fault.

**Comment by kelisiya** [comment]
> it works fine for me. The error you met seems like you are using 5 scales in RPN so the calculated size is 3*5=15. But it should be 4 scales set in `configs/BASE_RCNN_{}4gpu.yaml` which is loaded in L70 in `tools/test_net.py`. I suggest you to check your config file.



> it works fine for me. The error you met seems like you are using 5 scales in RPN so the calculated size is 3*5=15. But it should be 4 scales set in `configs/BASE_RCNN_{}4gpu.yaml` which is loaded in L70 in `tools/test_net.py`. I suggest you to check your config file.


I have another question，when I test the code ， other error about：
```
Traceback (most recent call last):
  File "tools/test_net.py", line 128, in <module>
    main()
  File "tools/test_net.py", line 122, in main
    output_folder=output_folder,
  File "/data/home/jxie/mega.pytorch/mega_core/engine/inference.py", line 94, in inference
    predictions = compute_on_dataset(model, data_loader, device, bbox_aug, cfg.MODEL.VID.METHOD, inference_timer)
  File "/data/home/jxie/mega.pytorch/mega_core/engine/inference.py", line 38, in compute_on_dataset
    output = model(images)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/home/jxie/mega.pytorch/mega_core/modeling/detector/generalized_rcnn_mega.py", line 78, in forward
    return self._forward_test(images["cur"], infos)
  File "/data/home/jxie/mega.pytorch/mega_core/modeling/detector/generalized_rcnn_mega.py", line 212, in _forward_test
    proposals_ref = cat_boxlist(list(self.proposals))
  File "/data/home/jxie/mega.pytorch/mega_core/structures/boxlist_ops.py", line 115, in cat_boxlist
    assert all(bbox.size == size for bbox in bboxes)
AssertionError
```
The error comes from dataset？My dataset have 2017 and 2015 DET ， VID；

**Comment by Scalsol** [comment]
> 
> 
> > it works fine for me. The error you met seems like you are using 5 scales in RPN so the calculated size is 3*5=15. But it should be 4 scales set in `configs/BASE_RCNN_{}4gpu.yaml` which is loaded in L70 in `tools/test_net.py`. I suggest you to check your config file.
> 
> > it works fine for me. The error you met seems like you are using 5 scales in RPN so the calculated size is 3*5=15. But it should be 4 scales set in `configs/BASE_RCNN_{}4gpu.yaml` which is loaded in L70 in `tools/test_net.py`. I suggest you to check your config file.
> 
> I have another question，when I test the code ， other error about：
> 
> ```
> Traceback (most recent call last):
>   File "tools/test_net.py", line 128, in <module>
>     main()
>   File "tools/test_net.py", line 122, in main
>     output_folder=output_folder,
>   File "/data/home/jxie/mega.pytorch/mega_core/engine/inference.py", line 94, in inference
>     predictions = compute_on_dataset(model, data_loader, device, bbox_aug, cfg.MODEL.VID.METHOD, inference_timer)
>   File "/data/home/jxie/mega.pytorch/mega_core/engine/inference.py", line 38, in compute_on_dataset
>     output = model(images)
>   File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/data/home/jxie/mega.pytorch/mega_core/modeling/detector/generalized_rcnn_mega.py", line 78, in forward
>     return self._forward_test(images["cur"], infos)
>   File "/data/home/jxie/mega.pytorch/mega_core/modeling/detector/generalized_rcnn_mega.py", line 212, in _forward_test
>     proposals_ref = cat_boxlist(list(self.proposals))
>   File "/data/home/jxie/mega.pytorch/mega_core/structures/boxlist_ops.py", line 115, in cat_boxlist
>     assert all(bbox.size == size for bbox in bboxes)
> AssertionError
> ```
> 
> The error comes from dataset？My dataset have 2017 and 2015 DET ， VID；

Have you changed the default test dataset? If not, I don't know why you encounter this error... This error may be caused by **the image in the same video clip** you used to generate the candidate boxes is of different size so the boxes generated could not be concatenated. But in ImageNet VID this propoerty is assured.

**Comment by kelisiya** [comment]
> > > it works fine for me. The error you met seems like you are using 5 scales in RPN so the calculated size is 3*5=15. But it should be 4 scales set in `configs/BASE_RCNN_{}4gpu.yaml` which is loaded in L70 in `tools/test_net.py`. I suggest you to check your config file.
> > 
> > 
> > > it works fine for me. The error you met seems like you are using 5 scales in RPN so the calculated size is 3*5=15. But it should be 4 scales set in `configs/BASE_RCNN_{}4gpu.yaml` which is loaded in L70 in `tools/test_net.py`. I suggest you to check your config file.
> > 
> > 
> > I have another question，when I test the code ， other error about：
> > ```
> > Traceback (most recent call last):
> >   File "tools/test_net.py", line 128, in <module>
> >     main()
> >   File "tools/test_net.py", line 122, in main
> >     output_folder=output_folder,
> >   File "/data/home/jxie/mega.pytorch/mega_core/engine/inference.py", line 94, in inference
> >     predictions = compute_on_dataset(model, data_loader, device, bbox_aug, cfg.MODEL.VID.METHOD, inference_timer)
> >   File "/data/home/jxie/mega.pytorch/mega_core/engine/inference.py", line 38, in compute_on_dataset
> >     output = model(images)
> >   File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
> >     result = self.forward(*input, **kwargs)
> >   File "/data/home/jxie/mega.pytorch/mega_core/modeling/detector/generalized_rcnn_mega.py", line 78, in forward
> >     return self._forward_test(images["cur"], infos)
> >   File "/data/home/jxie/mega.pytorch/mega_core/modeling/detector/generalized_rcnn_mega.py", line 212, in _forward_test
> >     proposals_ref = cat_boxlist(list(self.proposals))
> >   File "/data/home/jxie/mega.pytorch/mega_core/structures/boxlist_ops.py", line 115, in cat_boxlist
> >     assert all(bbox.size == size for bbox in bboxes)
> > AssertionError
> > ```
> > 
> > 
> > The error comes from dataset？My dataset have 2017 and 2015 DET ， VID；
> 
> Have you changed the default test dataset? If not, I don't know why you encounter this error... This error may be caused by **the image in the same video clip** you used to generate the candidate boxes is of different size so the boxes generated could not be concatenated. But in ImageNet VID this propoerty is assured.

```
Had processed 176126 imagesHad processed 176126 images

88176
176126
  0%|?                                                                                                           | 15/10994 [00:05<1:12:14,  2.53it/s]
Traceback (most recent call last):
  File "tools/test_net.py", line 128, in <module>
    main()
  File "tools/test_net.py", line 122, in main
    output_folder=output_folder,
  File "/data/home/jxie/mega.pytorch/mega_core/engine/inference.py", line 94, in inference
    predictions = compute_on_dataset(model, data_loader, device, bbox_aug, cfg.MODEL.VID.METHOD, inference_timer)
  File "/data/home/jxie/mega.pytorch/mega_core/engine/inference.py", line 38, in compute_on_dataset
    output = model(images)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/home/jxie/mega.pytorch/mega_core/modeling/detector/generalized_rcnn_mega.py", line 78, in forward
    return self._forward_test(images["cur"], infos)
  File "/data/home/jxie/mega.pytorch/mega_core/modeling/detector/generalized_rcnn_mega.py", line 212, in _forward_test
    proposals_ref = cat_boxlist(list(self.proposals))
  File "/data/home/jxie/mega.pytorch/mega_core/structures/boxlist_ops.py", line 118, in cat_boxlist
    assert all(bbox.size == size for bbox in bboxes)
AssertionError

```
The datasets ok , but the error looks like 2 gpus process datasets?
I load the  BASE_RCNN_4gpu.yaml rename BASE_RCNN_2gpu.yaml

**Comment by kelisiya** [comment]
> > > 这对我来说可以。您遇到的错误似乎是您在RPN中使用了5个比例，因此计算出的大小为3 * 5 = 15。但是应该`configs/BASE_RCNN_{}4gpu.yaml`在L70中加载4个标尺`tools/test_net.py`。我建议您检查您的配置文件。
> > 
> > 
> > > 这对我来说可以。您遇到的错误似乎是您在RPN中使用了5个比例，因此计算出的大小为3 * 5 = 15。但是应该`configs/BASE_RCNN_{}4gpu.yaml`在L70中加载4个标尺`tools/test_net.py`。我建议您检查您的配置文件。
> > 
> > 
> > 当我测试代码时，我还有另一个问题，关于以下其他错误：
> > ```
> > Traceback (most recent call last):
> >   File "tools/test_net.py", line 128, in <module>
> >     main()
> >   File "tools/test_net.py", line 122, in main
> >     output_folder=output_folder,
> >   File "/data/home/jxie/mega.pytorch/mega_core/engine/inference.py", line 94, in inference
> >     predictions = compute_on_dataset(model, data_loader, device, bbox_aug, cfg.MODEL.VID.METHOD, inference_timer)
> >   File "/data/home/jxie/mega.pytorch/mega_core/engine/inference.py", line 38, in compute_on_dataset
> >     output = model(images)
> >   File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
> >     result = self.forward(*input, **kwargs)
> >   File "/data/home/jxie/mega.pytorch/mega_core/modeling/detector/generalized_rcnn_mega.py", line 78, in forward
> >     return self._forward_test(images["cur"], infos)
> >   File "/data/home/jxie/mega.pytorch/mega_core/modeling/detector/generalized_rcnn_mega.py", line 212, in _forward_test
> >     proposals_ref = cat_boxlist(list(self.proposals))
> >   File "/data/home/jxie/mega.pytorch/mega_core/structures/boxlist_ops.py", line 115, in cat_boxlist
> >     assert all(bbox.size == size for bbox in bboxes)
> > AssertionError
> > ```
> > 
> > 
> > 错误来自数据集？我的数据集有2017年和2015年DET，VID；
> 
> 您是否更改了默认测试数据集？如果不是，我不知道您为什么会遇到此错误...此错误可能是由您用来生成候选框**的同一视频剪辑中的图像**大小不同导致的，因此无法串联生成的框。但是在ImageNet VID中可以确保这种特性。

The error seems to come from I use single GPU but set up test batch = 8 ， train and test don't support multy batch？

**Comment by kelisiya** [comment]
> > > it works fine for me. The error you met seems like you are using 5 scales in RPN so the calculated size is 3*5=15. But it should be 4 scales set in `configs/BASE_RCNN_{}4gpu.yaml` which is loaded in L70 in `tools/test_net.py`. I suggest you to check your config file.
> > 
> > 
> > > it works fine for me. The error you met seems like you are using 5 scales in RPN so the calculated size is 3*5=15. But it should be 4 scales set in `configs/BASE_RCNN_{}4gpu.yaml` which is loaded in L70 in `tools/test_net.py`. I suggest you to check your config file.
> > 
> > 
> > I have another question，when I test the code ， other error about：
> > ```
> > Traceback (most recent call last):
> >   File "tools/test_net.py", line 128, in <module>
> >     main()
> >   File "tools/test_net.py", line 122, in main
> >     output_folder=output_folder,
> >   File "/data/home/jxie/mega.pytorch/mega_core/engine/inference.py", line 94, in inference
> >     predictions = compute_on_dataset(model, data_loader, device, bbox_aug, cfg.MODEL.VID.METHOD, inference_timer)
> >   File "/data/home/jxie/mega.pytorch/mega_core/engine/inference.py", line 38, in compute_on_dataset
> >     output = model(images)
> >   File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
> >     result = self.forward(*input, **kwargs)
> >   File "/data/home/jxie/mega.pytorch/mega_core/modeling/detector/generalized_rcnn_mega.py", line 78, in forward
> >     return self._forward_test(images["cur"], infos)
> >   File "/data/home/jxie/mega.pytorch/mega_core/modeling/detector/generalized_rcnn_mega.py", line 212, in _forward_test
> >     proposals_ref = cat_boxlist(list(self.proposals))
> >   File "/data/home/jxie/mega.pytorch/mega_core/structures/boxlist_ops.py", line 115, in cat_boxlist
> >     assert all(bbox.size == size for bbox in bboxes)
> > AssertionError
> > ```
> > 
> > 
> > The error comes from dataset？My dataset have 2017 and 2015 DET ， VID；
> 
> Have you changed the default test dataset? If not, I don't know why you encounter this error... This error may be caused by **the image in the same video clip** you used to generate the candidate boxes is of different size so the boxes generated could not be concatenated. But in ImageNet VID this propoerty is assured.

The error seems to come from I use single GPU but set up test batch = 8 ， train and test don't support multy batch？

**Comment by Scalsol** [comment]
Yes, currently 1 gpu could only hold 1 image and I've mentioned it on the **usage** part of README :) Maybe an assertion error need to be triggered to warn people to not put more than 1 image on 1 gpu...

**Comment by kelisiya** [comment]
> Yes, currently 1 gpu could only hold 1 image and I've mentioned it on the **usage** part of README :) Maybe an assertion error need to be triggered to warn people to not put more than 1 image on 1 gpu...

 :)I can't wait to try this code,therefore ignored some details.Thank you.

**Comment by joe660** [comment]
> it works fine for me. The error you met seems like you are using 5 scales in RPN so the calculated size is 3*5=15. But it should be 4 scales set in `configs/BASE_RCNN_{}4gpu.yaml` which is loaded in L70 in `tools/test_net.py`. I suggest you to check your config file.


作者  这种信息怎样去除掉？？

2020-04-02 08:48:13,503 mega_core.utils.model_serialization INFO: backbone.body.layer1.0.bn1.running_mean loaded from backbone.body.layer1.0.bn1.running_mean                                
 of shape (64,)

2020-04-02 08:48:13,503 mega_core.utils.model_serialization INFO: backbone.body.layer1.0.bn1.running_var loaded from backbone.body.layer1.0.bn1.running_var of shape (64,)

2020-04-02 08:48:13,503 mega_core.utils.model_serialization INFO: backbone.body.layer1.0.bn1.weight loaded from backbone.body.layer1.0.bn1.weight of shape (64,)

2020-04-02 08:48:13,504 mega_core.utils.model_serialization INFO: backbone.body.layer1.0.bn2.bias  loaded fro
