### ISSUE TITLE
Why do not you add data augmentation like SELSA?

### ISSUE THREAD

**Issue by LiangHann** [Scalsol/mega.pytorch#8]
Why do not you add data augmentation like SELSA? Will you intend to do so?

**Comment by Scalsol** [comment]
SELSA is the only method that adopts data augmentation. For a fair comparison with other method, we don't treat data augmentation as a necessity. As now I'm working on another project so recently we will not perform any experiments with data augmentation :) The results with data augmentation may be available someday.
